### PR TITLE
Interconnect

### LINKED ISSUE #30: Interconnect data file format support
Add support for reading in data files exported by Lumerical

https://support.lumerical.com/hc/en-us/articles/360036107914-Optical-N-Port-S-Parameter-SPAR-INTERCONNECT-Element#toc_5

### PR DESCRIPTION
**Pull request by contagon**
Finished the plugin. Couldn't get the test that imports -> exports -> compares working exactly, but everything else seems to work great.

This should implement everything in #30.

### CODE REVIEW

**Comment by sequoiap** [comment]
The `simphony.persist` library, as I believe you've modeled some of this after, exports pickled files to a ".mdl" file. However, from a brief glance at the `simphony.plugins.interconnect` code, the docstring claims to also export data to a ".mdl" file but is using a simple numpy.savetxt function. If it's different from Simphony's expected ".mdl" format, perhaps we should change what `simphony.plugins.interconnect.export` function does, maybe saving just to a .txt file. (If this is what it does and I'm mistaking, could you update the docstring accordingly?)

**Comment by contagon** [comment]
Yup, just a docstring error. It does save to a .txt file. I'll fix it.

**Comment by contagon** [comment]
Fixed! Let me know if anything else needs changing

**Comment by AustP** [comment]
This doesn't work with our latest API changes, so I'm going to close this pull request.

**Pull request closed without merging**
